### ISSUE TITLE
后台无法返回前端问题

### ISSUE THREAD

**Issue by Kook-9527** [nezhahq/admin-frontend#17]
现在进去后台管理貌似没有地方返回前端了,要去网址栏删掉后面的才能回到前端,有点不方便，能不能把后台左上角的“哪吒监控”logo点击的链接改为返回前端?

**Comment by chrisvorer6** [comment]
现在进控制页面是新开标签页，不是跳转的，直接x掉就好了

**Comment by Kook-9527** [comment]
> 现在进控制页面是新开标签页，不是跳转的，直接x掉就好了

是的，我现在也是这样操作了，但是不能在一个页面上操作还是有点不方便，每次也要切换标签才能回到前端
