### ISSUE TITLE
关于通知的建议，希望采纳

### ISSUE THREAD

**Issue by vbskycn** [nezhahq/admin-frontend#31]
关于通知
对于熟悉json的用户来说确实不难，而且更加灵活
但大部分人还是有些难度

可否设置成通知账户的形式？
比如TG通知：设置一个TG通知的账户，设置所有的通知项目都可以选中这个账户，就可以了
邮件通知，设置一个自己的发信服务的账户，之后写通知规则都可以调用它
这样不是更加简单吗？

然后这里的通知函数，搞成选择性的，虽然少了一些灵活性，但是多了太多的便捷性
![image](https://github.com/user-attachments/assets/119b6f22-6d0e-4f3d-9115-283703345222)

居然升级V1了，重新写了代码，就让它成为国民级的应用吧，把上手难度降到最低
老大，加油

**Comment by uubulb** [comment]
国民级应用不敢当，没那个实力。
