### ISSUE TITLE
公开备注,过期无法自动续期

### ISSUE THREAD

**Issue by Kook-9527** [nezhahq/admin-frontend#40]
![IMG_2844](https://github.com/user-attachments/assets/f177336e-6693-43c5-a505-3f5b6e907118)
公开备注自动续期无效, 我使用的命令是下面这个
{
    "billingDataMod": {
        "startDate": "2023-12-07 09:50:17+08:00",
        "endDate": "2024-12-07 09:50:17+08:00",
        "autoRenewal": "1",
        "cycle": "年",
        "amount": "$9.89"
    },
    "planDataMod": {
        "bandwidth": "1000Mbps",
        "trafficVol": "2000GB/月",
        "trafficType": "2",
        "IPv4": "1",
        "IPv6": "1",
        "networkRoute": "",
        "extra": ""
    }
}

**Comment by Kook-9527** [comment]
![Uploading IMG_2844.jpeg…]()

**Comment by hamster1963** [comment]
目前仅使用endDate 来计算过期时间。

**Comment by Kook-9527** [comment]
好的，那就是说"autoRenewal": "1"这个参数其实是无效的
