### ISSUE TITLE
无法添加服务器

### ISSUE THREAD

**Issue by hmexy** [nezhahq/admin-frontend#55]
### 运行环境

Ubuntu-22.04-x64

### Nezha 版本

V1.1.6

### 描述问题

部署完成后进入后台点击安装命令后”出现Failed to execute 'insertBefore' on 'Node' （在节点上执行 insertBefore' 失败）：要插入新节点的节点不是该节点的子节点。”
在独立安装和docker环境下都会出现

### 复现步骤

![269eba0ae909766ac7206786b2d192d7](https://github.com/user-attachments/assets/de939676-49aa-4e53-af19-4b7fbd5c616a)

### 附加信息

<details></details>

### 验证

- [X] 我确认这是一个 nezha (哪吒面板) 的问题。
- [X] 我已经搜索了 Issues，并确认该问题之前没有被反馈过。

**Comment by uubulb** [comment]
可以在提供一下详细信息，比如环境 配置之类的

**Comment by hmexy** [comment]
在更换浏览器使用后已经解决问题，暂时无法复现，不确定是否为nezha问题
