### ISSUE TITLE
用户头像菜单的宽度不能自适应用户名长度

### ISSUE THREAD

**Issue by enterusernamecontinue** [nezhahq/admin-frontend#58]
### 运行环境

Debian GNU/Linux 11 KVM x86_64 6.7.8

### Nezha 版本

1.2.1

### 描述问题

<details>当用户名超过12字符时，点击用户头像弹出菜单的宽度不能自适应用户名的长度。</details>
![user_pop_menu](https://github.com/user-attachments/assets/8206958e-b987-4b95-8563-1ad05a268fa4)

### 复现步骤

用户名超过12字符时、后台点击用户头像。

### 附加信息

<details></details>

### 验证

- [x] 我确认这是一个 nezha (哪吒面板) 的问题。
- [X] 我已经搜索了 Issues，并确认该问题之前没有被反馈过。

**Comment by hamster1963** [comment]
<img width="181" alt="CleanShot 2024-12-17 at 21 49 23@2x" src="https://github.com/user-attachments/assets/3c1eea10-c637-47ec-9161-8d409558a198" />

已修复

**Comment by hamster1963** [comment]
不换行会长到夸张也，安啦..
